document: meta-test-family
version: 1
name: memcached
service:
    port: 11211
module:
    docker:
        start: "docker run -it -e CACHE_SIZE=128 -p 11211:11211"
        labels:
            description: "memcached is a high-performance, distributed memory"
            io.k8s.description: "memcached is a high-performance, distributed memory"
        source: https://github.com/container-images/memcached.git
        container: docker.io/modularitycontainers/memcached

    openshift:
        container: docker.io/modularitycontainers/memcached
